[package]
name = "jam"
version = "0.1.0"
edition = "2024"

[[bench]]
name = "varints"
harness = false

[dependencies]
jam_derive = { path = "./jam_derive" }

[dev-dependencies]
criterion = { version = "0.8.2" }
rand = { version = "0.10.0" }
